[package]
name = "rusche"
version = "0.5.0"
edition = "2021"
license = "MIT"
authors = ["Chan Ryu"]
description = "A lightweight Scheme interpreter embeddable in Rust applications"
readme = "README.md"
repository = "https://github.com/chanryu/rusche"
keywords = ["interpreter", "lisp", "scheme", "scripting", "scripting-language"]
categories = ["compilers", "config", "parser-implementations", "parsing"]
include = ["/src", "/examples", "/tests", "LICENSE", "README.md"]

[workspace]
members = ["crates/rusche-cli"]
resolver = "2"

[dependencies]

[dev-dependencies]
rand = "0.8"

[lib]
name = "rusche"
