(define (fizzbuzz-eval n)
    (define (mod0 n m) (= (% n m) 0))
    (cond ((mod0 n 15) "FizzBuzz")
          ((mod0 n 3) "Fizz")
          ((mod0 n 5) "Buzz")
          (#t n)))
(let ((n 0))
    (set! n (+ n 1))
    (while (< n 100)
        (println (fizzbuzz-eval n))
        (set! n (+ n 1))))
